server:
  port: 9090

spring:
  application:
    name: country-backend
  datasource:
    url: jdbc:mysql://localhost:3306/country_info?createDatabaseIfNotExist=true
    username: root
    password: H@si0116
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
